version: '3'

services:
    db:
        image: mariadb:10.3
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "./my.cnf:/etc/mysql/my.cnf"
        environment:
            MYSQL_PASSWORD: admin
            MYSQL_DATABASE: dashboardit
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            
        ports:
            - 3306:3306
        networks:
            - symfony
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./symfony/:/var/www/symfony/
       
        networks:
            - symfony
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./symfony/:/var/www/symfony/
        ports:
            - 8001:80
        networks:
            - symfony

volumes:
    db_app:

networks:
    symfony: