<?php

namespace ContainerDxdnnhm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BG4u8ISService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bG4u8IS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bG4u8IS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'clientsRepository' => ['privates', 'App\\Repository\\ClientsRepository', 'getClientsRepositoryService', true],
        ], [
            'clientsRepository' => 'App\\Repository\\ClientsRepository',
        ]);
    }
}
