<?php

namespace ContainerDxdnnhm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Tae1Oi4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Tae1Oi4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Tae1Oi4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'host' => ['privates', '.errored..service_locator.Tae1Oi4.App\\Entity\\Hosts', NULL, 'Cannot autowire service ".service_locator.Tae1Oi4": it references class "App\\Entity\\Hosts" but no such service exists.'],
        ], [
            'host' => 'App\\Entity\\Hosts',
        ]);
    }
}
