<?php

namespace ContainerDxdnnhm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccountsManagersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.c8ujQRB.App\Entity\AccountsManagers' shared service.
     *
     * @return \App\Entity\AccountsManagers
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.c8ujQRB": it references class "App\\Entity\\AccountsManagers" but no such service exists.');
    }
}
