<?php

namespace ContainerDxdnnhm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.NCyIbkW.App\Entity\Clients' shared service.
     *
     * @return \App\Entity\Clients
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.NCyIbkW": it references class "App\\Entity\\Clients" but no such service exists.');
    }
}
