<?php

namespace ContainerDxdnnhm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDomainsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._5KbXZp.App\Entity\Domains' shared service.
     *
     * @return \App\Entity\Domains
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator._5KbXZp": it references class "App\\Entity\\Domains" but no such service exists.');
    }
}
