<?php

namespace ContainerDxdnnhm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHostsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Tae1Oi4.App\Entity\Hosts' shared service.
     *
     * @return \App\Entity\Hosts
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Tae1Oi4": it references class "App\\Entity\\Hosts" but no such service exists.');
    }
}
