<?php

namespace ContainerDxdnnhm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ESSPwr_.App\Entity\Projects' shared service.
     *
     * @return \App\Entity\Projects
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ESSPwr_": it references class "App\\Entity\\Projects" but no such service exists.');
    }
}
