<?php

namespace ContainerDxdnnhm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1OunK_7.App\Entity\Servers' shared service.
     *
     * @return \App\Entity\Servers
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.1OunK_7": it references class "App\\Entity\\Servers" but no such service exists.');
    }
}
