<?php

namespace Container05Xxg9h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ESSPwrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ESSPwr_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ESSPwr_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'project' => ['privates', '.errored..service_locator.ESSPwr_.App\\Entity\\Projects', NULL, 'Cannot autowire service ".service_locator.ESSPwr_": it references class "App\\Entity\\Projects" but no such service exists.'],
        ], [
            'project' => 'App\\Entity\\Projects',
        ]);
    }
}
