<?php

namespace Container05Xxg9h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QeXc3uqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QeXc3uq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QeXc3uq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'hostsRepository' => ['privates', 'App\\Repository\\HostsRepository', 'getHostsRepositoryService', true],
        ], [
            'hostsRepository' => 'App\\Repository\\HostsRepository',
        ]);
    }
}
