<?php

namespace Container05Xxg9h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5KbXZpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._5KbXZp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._5KbXZp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'domain' => ['privates', '.errored..service_locator._5KbXZp.App\\Entity\\Domains', NULL, 'Cannot autowire service ".service_locator._5KbXZp": it references class "App\\Entity\\Domains" but no such service exists.'],
        ], [
            'domain' => 'App\\Entity\\Domains',
        ]);
    }
}
